export const POKEMON_LOAD ="POKEMON_LOAD";

export const GET_ALL_POKEMON_SUCCESS="GET_ALL_POKEMON_SUCCESS";
export const GET_ALL_POKEMON_FAIL = "GET_ALL_POKEMON_FAIL";

export const GET_POKEMON_SUCCESS="GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAIL = "GET_POKEMON_FAIL";


